# clog project configuration
# This file should be committed to version control to share project identity with your team

uuid: b2e1df3d-4961-4f7c-821f-f12bd9a98437
display_name: fighters-fight
created_at: 2026-02-14T21:26:11.115464Z

